-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 11:16:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_caiv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_caiv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_caiv` DEFAULT CHARACTER SET utf8 ;
USE `db_caiv` ;

-- -----------------------------------------------------
-- Table `db_caiv`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caiv`.`tb_usuario` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caiv`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caiv`.`tb_tema` (
  `id_tema` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_tema` VARCHAR(255) NOT NULL,
  `sub_tema` VARCHAR(255) NULL,
  PRIMARY KEY (`id_tema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_caiv`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_caiv`.`tb_postagem` (
  `id_postagem` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NULL,
  `tema_id` BIGINT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `referencia` VARCHAR(255) NULL,
  `data_hora` TIMESTAMP NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_tb_postagem_tb_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_tema1_idx` (`tema_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_caiv`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_tema1`
    FOREIGN KEY (`tema_id`)
    REFERENCES `db_caiv`.`tb_tema` (`id_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
